name: Language Build

on:
  push:
    paths:
      - "languages/**"
      - "converter/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Python deps
        run: |
          cd converter
          python3 -m pip install -r requirements.txt

      - name: Convert YAML -> ARB & TS
        run: |
          cd converter
          python3 convert.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: language-artifacts
          path: |
            converter/flutter_output
            converter/qml_output
