name: Generate Language Files

on:
  push:
    paths:
      - "languages/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Python deps
        run: |
          python3 -m pip install --upgrade pip
          pip install pyyaml

      - name: Convert YAML -> ARB & TS
        run: |
          cd converter
          python3 convert.py

      - name: Commit generated files
        run: |
          git config --global user.name "Khanhdtr"
          git config --global user.email "khanhdtr93@github.com"
          git add converter/flutter_output converter/qml_output
          git commit -m "Auto generate language files" || echo "No changes"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
